# Copyright (C) 2020 Ola Benderius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: '2'

services:
  video-h264-replay-amd64:
    build:
      context: https://github.com/chalmers-revere/opendlv-video-h264-replay.git#v0.0.1
      dockerfile: Dockerfile.amd64
    restart: on-failure
    network_mode: "host"
    ipc: "host"
    volumes:
      - ~/kiwi-recordings:/opt/recordings
      - /tmp:/tmp
    environment:
      - DISPLAY=${DISPLAY}
    # --verbose removed from the command below to not send the original video output
    # if verbose is removed use docker-compose -f h264-replay-viewer.yml up video-h264-replay-amd64 to start
    command: "--cid=111 --name=img.argb /opt/recordings/2020-03-24_131923-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/2020-03-24_132034-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/2020-03-24_132318-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/2020-03-24_132647-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/2020-03-24_133032-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/2020-03-24_133222-video-all.rec"
#
#    command: "--cid=111 --name=img.argb /opt/recordings/dyn_2020-05-14_123726-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/dyn_2020-05-14_123857-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/dyn_2020-05-14_123932-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task1_2020-03-24_150754-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task1_2020-03-24_150929-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task2_2020-05-14_121543-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task2_2020-05-14_122419-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task3_2020-05-14_123249-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task3_2020-05-14_123331-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task3_2020-05-14_123419-video-all.rec"
#    command: "--cid=111 --name=img.argb /opt/recordings/task3_2020-05-14_123547-video-all.rec"

  vehicle-view:
    image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
    restart: on-failure
    network_mode: host
    volumes:
      - ~/recordings:/opt/vehicle-view/recordings 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8081 
