version: "3.6"

services:
  sim-global:
    image: chalmersrevere/opendlv-sim-global-amd64:v0.0.7
    network_mode: "host"
    command: "/usr/bin/opendlv-sim-global --cid=111 --freq=50 --frame-id=0 --x=0.3 --y=0.6 --yaw=0.0 --timemod=1.0"

  sim-motor-kiwi:
    image: chalmersrevere/opendlv-sim-motor-kiwi-amd64:v0.0.7
    network_mode: "host"
    command: "/usr/bin/opendlv-sim-motor-kiwi --cid=111 --freq=200 --frame-id=0 --timemod=1.0"

  logic-pathfollower-kiwi:
    image: opendlv-logic-pathfollower-kiwi
    ipc: "host"
    network_mode: "host"
    volumes:
      - ./simulation-map.txt:/opt/simulation-map.txt
      - /tmp:/tmp
    environment:
      - DISPLAY=${DISPLAY}
    command: "/usr/bin/opendlv-logic-pathfollower-kiwi --cid=111 --freq=10 --frame-id=0 --map-file=/opt/simulation-map.txt --start-x=0.3 --start-y=0.6 --end-x=5.5 --end-y=0.5 --timemod=1.0 --verbose"

  opendlv-kiwi-view:
    image: chrberger/opendlv-kiwi-view-webrtc-multi:v0.0.6
    network_mode: "host"
    volumes:
      - ~/recordings:/opt/vehicle-view/recordings
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8081
      - OD4SESSION_CID=111
      - PLAYBACK_OD4SESSION_CID=253
