version: "3.6"

services:
  sim-global-two:
    image: chalmersrevere/opendlv-sim-global-amd64:v0.0.7
    network_mode: "host"
    command: "/usr/bin/opendlv-sim-global --cid=112 --freq=50 --timemod=0.1 --frame-id=0 --x=0.25 --y=-3.5 --yaw=0 --extra-cid-out=111:1"

  opendlv-logic-steering-control-two:
    image: opendlv-logic-steering-control
    network_mode: "host"
    command: "/usr/bin/opendlv-logic-steering-control --cid=112 --kf=30.0 --kn=13.5 --ki=36.0 --timemod=0.1"

  sim-motor-kiwi-two:
    image: chalmersrevere/opendlv-sim-motor-kiwi-amd64:v0.0.7
    network_mode: "host"
    command: "/usr/bin/opendlv-sim-motor-kiwi --cid=112 --freq=200 --timemod=0.1 --frame-id=0"

  opendlv-kiwi-view-two:
    image: chrberger/opendlv-kiwi-view-webrtc-multi:v0.0.6
    network_mode: "host"
    volumes:
      - ~/recordings:/opt/vehicle-view/recordings
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8082
      - OD4SESSION_CID=112
      - PLAYBACK_OD4SESSION_CID=254

